# Generated by Django 5.0.1 on 2024-03-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_grouppermissions_usergroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vendedor'), (2, 'Colaborador'), (3, 'Cliente')], null=True, verbose_name='Tipo'),
        ),
    ]
